config/routes.rb
CasaDanesa::Application.routes.draw do
  resources :blog_posts

  match '/', to: 'home#index', via: :get
  match '/home', to: 'home#index', via: :get
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  http_basic_authenticate_with name: 'eric', password: 'github readers only'

  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  def index
    @blog_posts = BlogPost.all
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to edit_blog_post_path(@blog_post), notice: 'Blog post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :draft_body, :published_body, :published_at)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = 'The Casa Danesa Project'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    "#{controller.controller_path} #{controller.action_name}"
  end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_form.html.haml
= form_for @blog_post do |f|
  - if @blog_post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blog_post.errors.count, "error")} prohibited this blog_post from being saved:"
      %ul
        - @blog_post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :draft_body
    = f.text_field :draft_body
  .field
    = f.label :published_at
    = @blog_post.published_at
  .field
    = f.label :updated_at
    = @blog_post.updated_at
  .field
    = f.label :created_at
    = @blog_post.created_at
  .actions
    = f.submit 'Save'

app/views/blog_posts/edit.html.haml
%h1 Editing blog_post

= render 'form'

= link_to 'Show', @blog_post
\|
= link_to 'Back', blog_posts_path

app/views/blog_posts/index.html.haml
%h1 Listing blog_posts

%table
  %tr
    %th Title
    %th Draft body,
    %th Published body
    %th Published at
    %th
    %th
    %th

  - @blog_posts.each do |blog_post|
    %tr
      %td= blog_post.title
      %td= blog_post.draft_body
      %td= blog_post.published_body
      %td= blog_post.published_at
      %td= link_to 'Show', blog_post
      %td= link_to 'Edit', edit_blog_post_path(blog_post)
      %td= link_to 'Destroy', blog_post, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Blog post', new_blog_post_path

app/views/blog_posts/new.html.haml
%h1 New blog_post

= render 'form'

= link_to 'Back', blog_posts_path

app/views/blog_posts/show.html.haml
%p
  %b Title
  = @blog_post.title
%p
  %b Draft body
  = @blog_post.draft_body
%p
  %b Published body
  = @blog_post.published_body
%p
  %b Published at
  = @blog_post.published_at

= link_to 'Edit', edit_blog_post_path(@blog_post)
\|
= link_to 'Back', blog_posts_path

app/views/home/index.html.haml
= image_tag 'Casa-Danesa-Logo.png'

.menu{style: 'margin: 50px'}
  = link_to 'Mahoney Southern Africa Adventure 2014', 'http://mahoney-southern-africa-2014.s3-website-us-west-1.amazonaws.com/index.html'

.version 0.3

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= @title
  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags

%body{class: body_class}

  #notice= notice

  = yield